"""actually add status column

Revision ID: 3b1904d63791
Revises: f27e07b45065
Create Date: 2026-06-11 00:37:14.054305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b1904d63791'
down_revision: Union[str, Sequence[str], None] = 'f27e07b45065'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluations', sa.Column('status', sa.String(),
    server_default='PENDING', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evaluations', 'status')
    # ### end Alembic commands ###
